const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const RECEIVE_TODOS = "RECEIVE_TODOS";
const SET_LOGGED_USER = "SET_LOGGED_USER";

export {
  ADD_TODO,
  TOGGLE_TODO,
  REMOVE_TODO,
  SET_LOGGED_USER,
  RECEIVE_TODOS,
};