const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const RECEIVE_TODOS = "RECEIVE_TODOS";


export {
  ADD_TODO,
  TOGGLE_TODO,
  REMOVE_TODO,
  RECEIVE_TODOS
};